baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'BJ Fontaneros'
theme = 'Ultramarine'

[params]
    brand = 'BJFontaneros_left.svg'
    contact_url = 'contact'
    copyright = '© 2024 BJ Fontaneros'
    autor_copyright = '@EEsto'
    autor_url = 'http://estasleyendoesto.github.io/'
    instagram = 'http://instagram.com'
    facebook = 'http://facebook.com'
    about = 'Nuestra empresa comenzó hace tres décadas, construyendo una reputación de confianza y calidad. Ofrecemos soluciones de fontanería eficientes y de alta calidad. Cada proyecto demuestra nuestro compromiso con la excelencia. Hoy, seguimos creciendo gracias al esfuerzo conjunto de padre e hijo.'

[menus]
    [[menus.main]]
        identifier = 'home'
        name = 'Fontanería'
        pageRef = '/'
        weight = '1'
    [[menus.main]]
        identifier = 'reforms'
        name = 'Reformas'
        pageRef = 'reforms'
        weight = '2'
    [[menus.main]]
        identifier = 'projects'
        name = 'Proyectos'
        pageRef = 'projects'
        weight = '3'
    [[menus.main]]
        identifier = 'contact'
        name = 'Contacto'
        pageRef = 'contact'
        weight = '4'